name: 'Sourcetoad - AWS S3 Delete After Action'
description: 'Delete S3 files older than a specific time.'
author: Sourcetoad
branding:
  color: 'gray-dark'
  icon: 'delete'

inputs:
  s3_bucket_name:
    description: 'S3 Bucket Name'
    required: true
  s3_prefix:
    description: 'S3 Prefix'
    default: ''
    required: false
  s3_delete_phrase:
    description: 'Files older than this phrase (ie -7days, -1month)'
    required: true
  aws_region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'
  no_dry_run:
    description: 'Must set to true for actual deletion to occur.'
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/delete.sh'
